name: Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!main'

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust this to your .NET version

      - name: Install Nuke Global Tool
        run: dotnet tool install --global Nuke.GlobalTool

      - name: Run Nuke build
        run: ./.nuke/build.cmd Compile PublishGitHub --GitHubToken ${{ secrets.GITHUB_TOKEN }}
